name: Build & Deploy to Elastic Beanstalk

on:
  push:
    branches: [ main ]   # deploy when pushing to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'   # adjust if using 6.0 or 7.0

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --no-build --verbosity normal

      - name: Publish
        run: dotnet publish -c Release -o ./publish

      - name: Zip artifact
        run: zip -r deploy.zip ./publish/*

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: "AKIA3B4QLJXL5SMLPKJ7"
          aws-secret-access-key: "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"
          aws-region: "us-east-1"

      - name: Upload to S3
        run: aws s3 cp deploy.zip s3://my-beanstalk-bucket-app-ringinfotech/deploy-${{ github.sha }}.zip

      - name: Create new Beanstalk Application Version
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name my-dotnet-api \
            --version-label ${{ github.sha }} \
            --source-bundle S3Bucket="my-beanstalk-bucket-app-ringinfotech",S3Key="deploy-${{ github.sha }}.zip"

      - name: Deploy Application to Beanstalk Environment
        run: |
          aws elasticbeanstalk update-environment \
            --environment-name myapi-env \
            --version-label ${{ github.sha }}

          
